spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/springboot_template}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
